import { NgModule } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';

import {
  MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatToolbarModule,
  MatExpansionModule,
  MatProgressSpinnerModule,
  MatPaginatorModule,
  MatDialogModule,
  MatIconModule,
  MatSelectModule,
  MatListModule,
  MatDividerModule,
  MatGridListModule,
  MatAutocompleteModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatRadioModule,
  MatSlideToggleModule,
  MatStepperModule,
  MatTabsModule,
  MatProgressBarModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTableModule,
} from '@angular/material';

@NgModule({
  exports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatDialogModule,
    MatIconModule,
    MatDividerModule,
    MatSelectModule,
    FlexLayoutModule,
    MatListModule,
    MatGridListModule,
    MatAutocompleteModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatTabsModule,
    MatProgressBarModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTableModule,
  ]
})
export class AngularMaterialModule {}
